- project:
    check: &jobs
      jobs:
        - run-test-command:
            vars:
              test_command:
                - sudo npm install -g yarn
                - yarn install
                - yarn test
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-javascript
    gate: *jobs
