- project:
    check: &jobs
      jobs:
        - run-test-command:
            vars:
              test_command:
                - npm install
                - npm run test
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-javascript
    gate: *jobs
